# swagger 配置
swagger:
  enabled: true
  title: Gomoney Swagger API
  gateway: http://${GATEWAY-HOST:127.0.0.1}:${GATEWAY-PORT:9999}
  token-url: ${swagger.gateway}/gomoney-oauth2/oauth2/token
  scope: message.read
